#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: autogen
# autospec version: v3
# autospec commit: c1050fe
#
Name     : clr-network-troubleshooter
Version  : 20
Release  : 22
URL      : https://github.com/clearlinux/clr-network-troubleshooter/archive/v20/clr-network-troubleshooter-20.tar.gz
Source0  : https://github.com/clearlinux/clr-network-troubleshooter/archive/v20/clr-network-troubleshooter-20.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: clr-network-troubleshooter-bin = %{version}-%{release}
Requires: clr-network-troubleshooter-license = %{version}-%{release}
Requires: bind-utils
Requires: curl
Requires: iputils
Requires: perl
BuildRequires : bind-utils
BuildRequires : curl
BuildRequires : iputils
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# clr-network-troubleshooter
This is a tool to perform basic networking tests on a Clear Linux system. It attempts to diagnose common issues and provide suggested actions to resolve them.

%package bin
Summary: bin components for the clr-network-troubleshooter package.
Group: Binaries
Requires: clr-network-troubleshooter-license = %{version}-%{release}

%description bin
bin components for the clr-network-troubleshooter package.


%package license
Summary: license components for the clr-network-troubleshooter package.
Group: Default

%description license
license components for the clr-network-troubleshooter package.


%prep
%setup -q -n clr-network-troubleshooter-20
cd %{_builddir}/clr-network-troubleshooter-20

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1701943080
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
%autogen --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1701943080
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/clr-network-troubleshooter
cp %{_builddir}/clr-network-troubleshooter-%{version}/COPYING %{buildroot}/usr/share/package-licenses/clr-network-troubleshooter/4cc77b90af91e615a64ae04893fdffa7939db84c || :
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/clr-network-troubleshooter

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/clr-network-troubleshooter/4cc77b90af91e615a64ae04893fdffa7939db84c
